server:
  port: 16115

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos:8848}
  application:
    name: ts-admin-user-service

swagger:
  controllerPackage: adminuser.controller