version: '3'
services:

#  rabbitmq:
#    image: rabbitmq:management
#    ports:
#      - 5672:5672
#      - 15672:15672
#    networks:
#      - train-ticket

  # kafka:
  #   container_name: kafka
  #   image: spotify/kafka:latest
  #   ports:
  #    - 2181:2181
  #    - 9092:9092
  #   networks:
  #     - train-ticket

#  zipkin:
#    image: openzipkin/zipkin
#    ports:
#      - 9411:9411
#    networks:
#      - train-ticket

  nacos:
    image: nacos/nacos-server:2.0.1
    ports:
      - 8848:8848
      - 9848:9848
    environment:
      - MODE=standalone
    networks:
      - train-ticket

  redis:
    image: redis:7.0.0
    ports:
      - 6379:6379
    networks:
      - train-ticket

  ts-ui-dashboard:
    image: stream/ts-ui-dashboard:base
    depends_on:
      ts-gateway-service:
        condition: service_started
    ports:
      - 8080:8080
    networks:
      - train-ticket

  ts-auth-service:
    image: stream/ts-auth-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 12340:12340
    networks:
      - train-ticket

  ts-auth-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-user-service:
    image: stream/ts-user-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 12342:12342
    networks:
      - train-ticket

  ts-user-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-verification-code-service:
    image: stream/ts-verification-code-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 15678:15678
    networks:
      - train-ticket


#  ts-account-mongo:
#    image: mongo
#    networks:
#      - train-ticket

  ts-route-service:
    image: stream/ts-route-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
         - 11178:11178
    networks:
      - train-ticket

  ts-route-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
        - train-ticket

  ts-contacts-service:
    image: stream/ts-contacts-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 12347:12347
    networks:
      - train-ticket

  ts-contacts-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-order-service:
    image: stream/ts-order-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 12031:12031
    networks:
      - train-ticket

  ts-order-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket


  ts-order-other-service:
    image: stream/ts-order-other-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 12032:12032
    networks:
      - train-ticket

  ts-order-other-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket


  ts-config-service:
    image: stream/ts-config-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 15679:15679
    networks:
      - train-ticket

  ts-config-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket
    command: "--innodb_use_native_aio=0"

  ts-station-service:
    image: stream/ts-station-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 12345:12345
    networks:
      - train-ticket

  ts-station-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-train-service:
    image: stream/ts-train-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 14567:14567
    networks:
      - train-ticket

  ts-train-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-travel-service:
    image: stream/ts-travel-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 12346:12346
    networks:
      - train-ticket

  ts-travel-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket
    command: "--innodb_use_native_aio=0"

  ts-travel2-service:
    image: stream/ts-travel2-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 16346:16346
    networks:
      - train-ticket

  ts-travel2-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket
    command: "--innodb_use_native_aio=0"

  ts-preserve-service:
    image: stream/ts-preserve-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 14568:14568
    networks:
      - train-ticket

  ts-preserve-other-service:
    image: stream/ts-preserve-other-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 14569:14569
    networks:
      - train-ticket


  ts-basic-service:
    image: stream/ts-basic-service:base
    depends_on:
      nacos:
          condition: service_started
    ports:
      - 15680:15680
    networks:
        - train-ticket

#  ts-ticketinfo-service:
#        image: stream/ts-ticketinfo-service:base
#        
#        ports:
#          - 15681:15681
#        networks:
#          - train-ticket

  ts-price-service:
    image: stream/ts-price-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 16579:16579
    networks:
      - train-ticket

  ts-price-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-notification-service:
    image: stream/ts-notification-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 17853:17853
    networks:
      - train-ticket

  ts-notification-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-security-service:
    image: stream/ts-security-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 11188:11188
    networks:
      - train-ticket

  ts-security-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-inside-payment-service:
    image: stream/ts-inside-payment-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 18673:18673
    networks:
      - train-ticket

  ts-inside-payment-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-execute-service:
    image: stream/ts-execute-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 12386:12386
    networks:
      - train-ticket

  ts-payment-service:
    image: stream/ts-payment-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 19001:19001
    networks:
      - train-ticket

  ts-payment-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-rebook-service:
    image: stream/ts-rebook-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 18886:18886
    networks:
      - train-ticket

  ts-rebook-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-cancel-service:
    image: stream/ts-cancel-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 18885:18885
    networks:
      - train-ticket

  ts-assurance-service:
    image: stream/ts-assurance-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 18890:18890
    networks:
      - train-ticket

  ts-assurance-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-seat-service:
    image: stream/ts-seat-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 18898:18898
    networks:
      - train-ticket

  ts-travel-plan-service:
    image: stream/ts-travel-plan-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 14322:14322
    networks:
      - train-ticket

#  ts-ticket-office-service:
#        image: stream/ts-ticket-office-service:base
#        
#        ports:
#          - 16108:16108
#        networks:
#          - train-ticket
#
#  ts-ticket-office-mongo:
#          image: mongo
#          networks:
#            - train-ticket

  ts-news-service:
    image: stream/ts-news-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 12862:12862
    networks:
      - train-ticket

  ts-news-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-voucher-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    expose:
      - "3306"
    networks:
      - train-ticket

  ts-voucher-service:
    image: stream/ts-voucher-service:base
    depends_on:
      nacos:
        condition: service_started
      ts-voucher-mysql:
        condition: service_started
      
    ports:
      - 16101:16101
    networks:
      - train-ticket

#  ts-food-map-service:
#        image: stream/ts-food-map-service:base
#        
#        ports:
#          - 18855:18855
#        networks:
#          - train-ticket
#
#  ts-food-map-mongo:
#          image: mongo
#          networks:
#            - train-ticket

  ts-route-plan-service:
    image: stream/ts-route-plan-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 14578:14578
    networks:
      - train-ticket

  ts-food-service:
    image: stream/ts-food-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 18856:18856
    networks:
      - train-ticket

  ts-consign-service:
    image: stream/ts-consign-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 16111:16111
    networks:
      - train-ticket

  ts-consign-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-consign-price-service:
    image: stream/ts-consign-price-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 16110:16110
    networks:
      - train-ticket

  ts-consign-price-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-food-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-admin-basic-info-service:
    image: stream/ts-admin-basic-info-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 18767:18767
    networks:
      - train-ticket

  ts-admin-order-service:
    image: stream/ts-admin-order-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 16112:16112
    networks:
      - train-ticket

  ts-admin-route-service:
    image: stream/ts-admin-route-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 16113:16113
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - train-ticket

  ts-admin-travel-service:
    image: stream/ts-admin-travel-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 16114:16114
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - train-ticket

  ts-admin-user-service:
    image: stream/ts-admin-user-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 16115:16115
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - train-ticket

  ts-avatar-service:
    image: stream/ts-avatar-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 17001:17001
    networks:
      - train-ticket

  ts-delivery-service:
    image: stream/ts-delivery-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 18807:18807
    networks:
      - train-ticket

  ts-delivery-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket
    command: "--innodb_use_native_aio=0"

  ts-food-delivery-service:
    image: stream/ts-food-delivery-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 18957:18957
    networks:
      - train-ticket

  ts-food-delivery-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket
    command: "--innodb_use_native_aio=0"

  ts-gateway-service:
    image: stream/ts-gateway-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 18888:18888
    networks:
      - train-ticket

  ts-gateway-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket
    command: "--innodb_use_native_aio=0"


  ts-station-food-service:
    image: stream/ts-station-food-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 18855:18855
    networks:
      - train-ticket

  ts-station-food-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket


  ts-train-food-service:
    image: stream/ts-train-food-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 19999:19999
    networks:
      - train-ticket

  ts-train-food-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

  ts-wait-order-service:
    image: stream/ts-wait-order-service:base
    depends_on:
      nacos:
        condition: service_started
    ports:
      - 17525:17525
    networks:
      - train-ticket
  
  ts-wait-order-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - train-ticket

networks:
    train-ticket:
      # driver: overlay
      driver: bridge





