server:
  port: 15678  # HTTP (Tomcat) port

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos:8848}
  application:
    name: ts-verification-code-service

swagger:
  controllerPackage: verifycode.controller