server:
  port: 16113

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos:8848}
  application:
    name: ts-admin-route-service

swagger:
  controllerPackage: adminroute.controller