version: '3'
services:
  ts-ui-dashboard:
    image: stream/ts-ui-dashboard:one-database
    ports:
      - 8080:8080
    networks:
      - train-ticket

networks:
    train-ticket:
      # driver: overlay
      driver: bridge